ТипФайла: "Сценарий"
ДанныеСценария:
    UID: "50352278-e476-4617-9c69-2babe0b5a366" 
    Имя: "I Config Enterprise"  
    Код: "000001002" 
    Проект: "Drive"
    ФункцияСистемы: "Drive automation testing"
    РазрешеноИспользоватьВДругихФункциях: "Yes" 
    UIDФункцияСистемы: "98999f57-13dc-11e8-aed1-005056a5c4e8"
    ПрофильПользователя: "Administrador" 
    УровеньОтчета1: "Drive"
    УровеньОтчета2: "Purchase"

ПараметрыСценария: 
    - ПараметрыСценария1:
        НомерСтроки: "1" 
        Имя: "RESPONSABLE IVA"      
        Значение: "Responsable de IVA / Persona Jurídica" 
        ТипПараметра: "Строка" 
        ИсходящийПараметр: "No" 
    - ПараметрыСценария2:
        НомерСтроки: "2" 
        Имя: "CIUDAD"      
        Значение: "BOGOTA, D.C." 
        ТипПараметра: "Строка" 
        ИсходящийПараметр: "No" 

ВложенныеСценарии:


ТекстСценария: |

    #language: en

    # Configuracion empresa
	And In the command interface I select "Empresa" "Empresas"
	Then "Empresas" window is opened
    And I go to line in "List" table
	    | 'Descripción' |
	    | 'Prueba' |
	And I select current line in "List" table
	Then "* (Empresa)" window is opened
	And I select [RESPONSABLE IVA] exact value from the drop-down list named "TipoEmpresa"
	And I input "38,004.00" text in "UVT" field
	And I select [CIUDAD] exact value from "Ciudad" drop-down list
	And I click "Save and close" button
-

