ТипФайла: "Сценарий"
ДанныеСценария:
    UID: "91dec40c-5910-4c09-9843-ae209c720863"  
    Имя: "I Config PCLM"  
    Код: "000001005" 
    Проект: "Drive"
    ФункцияСистемы: "Drive automation testing"
    РазрешеноИспользоватьВДругихФункциях: "Yes" 
    UIDФункцияСистемы: "98999f57-13dc-11e8-aed1-005056a5c4e8"
    ПрофильПользователя: "Gerencia" 
    УровеньОтчета1: "Drive"
    УровеньОтчета2: "Purchase"
		
ПараметрыСценария: 
   	- ПараметрыСценария1:
        НомерСтроки: "1" 
        Имя: "PCLM"      
        Значение: "140501" 
        ТипПараметра: "Строка" 
        ИсходящийПараметр: "No" 
    - ПараметрыСценария2:
        НомерСтроки: "2" 
        Имя: "DC"      
        Значение: "622501" 
        ТипПараметра: "Строка" 
        ИсходящийПараметр: "No" 
    - ПараметрыСценария3:
        НомерСтроки: "3" 
        Имя: "DIC"      
        Значение: 	"240801" 
        ТипПараметра: "Строка" 
        ИсходящийПараметр: "No" 
    - ПараметрыСценария4:
        НомерСтроки: "4" 
        Имя: "EDI"      
        Значение: 	"240802" 
        ТипПараметра: "Строка" 
        ИсходящийПараметр: "No"

ВложенныеСценарии:

ТекстСценария: |

#language: en

# Configuracion Cuenta de libro mayor
	And In the command interface I select "Empresa" "Producto de las cuentas del libro mayor"
 #Busca si existe o no 
	If "List" table contains line Then
		|	"Producto" |
		|	[PRODUCTO]	|
		And I go to line in "List" table
			| 'Producto' |
			| [PRODUCTO]  |
		And I select current line in "List" table
		Then "*" window is opened

	Else
		And I click the button named "FormCreate"
		Then "* (*)" window is opened
		And I click Select button of "Categoría de producto" field
		Then "Categorías de productos" window is opened
		And I go to line in "List" table
			| 'Descripción'			|
			| [CATEGORIA]	|
		And I select current line in "List" table
		And I click Select button of "Producto" field
		Then "Productos" window is opened
		And I move one level down in "List" table
		And I move one level up in "List" table
		And I move one level down in "List" table
		And I go to line in "List" table
			| 'Descripción'	|
			| [PRODUCTO] 	|
		And I select current line in "List" table
		Then "* (*)" window is opened


	# Numeros CLM Productos

	#PCLM
	And I click Select button of "Producto de la cuenta del libro mayor" field
	Then "Cuenta" window is opened
	And in the table "List" I click the button named "ListFind"
	Then "Find" window is opened
	And I input [PCLM] text in "F&ind" field
	And I click "&Find" button
	Then "Cuenta" window is opened
	And I go to line in "List" table
		| 'Código' |
		| [PCLM] |
	And I select current line in "List" table
	Then "*" window is opened

	#DC
	And I click Select button of "Devolución de la compra" field
	Then "Cuenta" window is opened
	And in the table "List" I click the button named "ListFind"
	Then "Find" window is opened
	And I input 	[DC] text in "F&ind" field
	And I click "&Find" button
	Then "Cuenta" window is opened
	And I go to line in "List" table
		| 'Código' |
		| 	[DC] 	|
	And I select current line in "List" table
	Then "*" window is opened

	#DIC
	And I click Select button of "Devolucion IVA compras" field
	Then "Cuenta" window is opened
	And in the table "List" I click the button named "ListFind"
	Then "Find" window is opened
	And I input [DIC] text in "F&ind" field
	And I click "&Find" button
	Then "Cuenta" window is opened
	And I go to line in "List" table
		| 'Código' |
		| [DIC] |
	And I select current line in "List" table
	Then "*" window is opened

	#EDI
	And I click Select button of "Entrada del IVA" field
	Then "Cuenta" window is opened
	And in the table "List" I click the button named "ListFind"
	Then "Find" window is opened
	And I input [EDI] text in "F&ind" field
	And I click "&Find" button
	Then "Cuenta" window is opened
	And I go to line in "List" table
		| 'Código' |
		| [EDI] |
	And I select current line in "List" table
	Then "*" window is opened

	And I click "Save and close" button 


