ТипФайла: "Сценарий"
ДанныеСценария:
    UID: "91dec40c-5910-4c09-9843-ae209c720863"  
    Имя: "I Config PCLM"  
    Код: "000001005" 
    Проект: "Drive"
    ФункцияСистемы: "Drive automation testing"
    РазрешеноИспользоватьВДругихФункциях: "Yes" 
    UIDФункцияСистемы: "98999f57-13dc-11e8-aed1-005056a5c4e8"
    ПрофильПользователя: "Gerencia" 
    УровеньОтчета1: "Drive"
    УровеньОтчета2: "Purchase"
		
ПараметрыСценария: 

ВложенныеСценарии:

ТекстСценария: |

#language: en

# Configuracion * de libro mayor
	And In the command interface I select "Company" "Product GL accounts"
 #Busca si existe o no 
 	If "List" table does not contain line Then
		|	"Product"	|
		|	[PRODUCTO]	|
		And I click the button named "FormCreate"
		Then "* (*)" window is opened
		And I click Select button of "Categoría de producto" field
		Then "Categorías de productos" window is opened
		And I go to line in "List" table
			| 'Descripción'			|
			| [CATEGORIA]	|
		And I select current line in "List" table
		And I click Select button of "Product" field
		Then "Products" window is opened
		And I move one level down in "List" table
		And I move one level up in "List" table
		And I move one level down in "List" table
		And I go to line in "List" table
			| 'Descripción'	|
			| [PRODUCTO] 	|
		And I select current line in "List" table
		Then "* (*)" window is opened
		
		And I click "Save and close" button 
	EndIf

	And I go to line in "List" table
		| 'Product'	|
		| [PRODUCTO]	|
	And I select current line in "List" table
	Then "*" window is opened




	# Numeros CLM Productos

	#PCLM
	And I click Select button of "Product GL account" field
	Then "*" window is opened
	And in the table "List" I click the button named "ListFind"
	Then "Find" window is opened
	And I input [PCLM] text in "F&ind" field
	And I click "&Find" button
	Then "*" window is opened
	And I go to line in "Hierarchy" table
		| 'Value'               |
		| 'Inventories' 				|
	And I go to line in "List" table
		| 'code' |
		| [PCLM] |
	And I select current line in "List" table
	Then "*" window is opened

	#DC
	And I click Select button of "Purchase return" field
	Then "*" window is opened
	And in the table "List" I click the button named "ListFind"
	Then "Find" window is opened
	And I input 	[DC] text in "F&ind" field
	And I click "&Find" button
	Then "*" window is opened
	And I go to line in "Hierarchy" table
		| 'Value'               |
		| 'Cost of sales' 				|
	And I go to line in "List" table
		| 'code' |
		| 	[DC] 	|
	And I select current line in "List" table
	Then "*" window is opened

	#DIC
	And I click Select button of "Devolucion IVA compras" field
	Then "*" window is opened
	And in the table "List" I click the button named "ListFind"
	Then "Find" window is opened
	And I input [DIC] text in "F&ind" field
	And I click "&Find" button
	Then "*" window is opened
	And I go to line in "Hierarchy" table
		| 'Value'               |
		| 'Taxes' 			|
	And I go to line in "List" table
		| 'code' |
		| [DIC] |
	And I select current line in "List" table
	Then "*" window is opened

	#EDI
	And I click Select button of "VAT Input" field
	Then "*" window is opened
	And in the table "List" I click the button named "ListFind"
	Then "Find" window is opened
	And I input [EDI] text in "F&ind" field
	And I click "&Find" button
	Then "*" window is opened
	And I go to line in "Hierarchy" table
		| 'Value'               |
		| 'Taxes' 			|
	And I go to line in "List" table
		| 'code' |
		| [EDI]		|
	And I select current line in "List" table
	Then "*" window is opened

	And I click "Save and close" button 


