ТипФайла: "Сценарий"
ДанныеСценария:
    UID: "1ab1e62b-c9b9-45c1-a3ec-bfdf3c65ba5b" 
    Имя: "I Config Product"
    Код: "000001004"
    Проект: "Drive"
    ФункцияСистемы: "Drive automation testing"
    РазрешеноИспользоватьВДругихФункциях: "Yes"
    UIDФункцияСистемы: "98999f57-13dc-11e8-aed1-005056a5c4e8"
    ПрофильПользователя: "Gerencia"  
    УровеньОтчета1: "Drive"
    УровеньОтчета2: "Purchase"

ПараметрыСценария: 

ВложенныеСценарии:

ТекстСценария: |
#language: en
 
    # configuracion producto
    And In the command interface I select "Production" "Products"
    Then "Products" window is opened
    And I go to line in "List" table
         | 'Description'  |
         | 	[PRODUCTO] 	| 
        And I select current line in "List" table
        Then "*(Product)" window is opened
        And I click Open button of "Product category" field
        Then "* (Product category)"window is opened

    # nombre de catergoria
        And I input [CATEGORIA] text in "Description" field 
        And I click "Save and close" button

        And I wait " * (Product category) *" window closing in 20 seconds
        Then "* (*)" window is opened
        And I move to "Additional data" tab
        And I move to "Invoicing" tab

    #RTE Fuente
        And I select "Compras Generales" exact value from "Concepto RTE en la Fuente Nacional " drop-down list
        
    #RTE ICA
        And I select "Fabricación de productos primarios de hierro y acero; fabricación de material de transporte" exact value from "Actividad retención ICA" drop-down list
        And I click "Save and close" button 